---
    - name: install apache2
      become: yes
      apt:
        name: apache2
        state: present
    - name: Create index.html
      template:
        src: templates/indexhtml.j2
        dest: "{{ ansible_user_dir }}/index.html"
    - name: Starting apache2
      become: true
      systemd:
        name: apache2
        enabled: true
        masked: no
    - name: Curl
      command: "curl {{ ansible_facts.default_ipv4.address }}"