---
- name: Install packeges
  hosts: webservers
  gather_facts: false
  become: yes
  tags: 
    - packeges
  tasks:

  - name: Ensure that required packeges are installed
    apt: 
      name:
        - net-tools
        - Curl
        - epel-release
        - ca-certificates
        - mc
      state: latest



- name: Start services
  hosts: nginx
  become: yes
  tasks:
  
  - name: Ensure that nginx installed
    apt: 
      name:
        - nginx
      state: latest

  - name: Current ip
    debug:
      msg: "https://{{ ansible_facts.default_ipv4.address }}:80"
  
  - name: Modyfy file
    shell:
      cmd: "echo hello > mynewfile.txt"
      chdir: "/root/"

  - name: Create file 2
    file:
      path: "/root/"
      owner: root
      group: root
      mode: "0644"
      state: touch

  - name: Change file text
    lineinfile:
      path: /root/mynewfile.txt
      regexp: '^hello'
      line: Helllo2
