---
---
- hosts: "all"
  roles:
    - apache
    
- name: Install packeges
  hosts: webservers
  gather_facts: false
  become: yes
  roles:
    - myrole

#or
- name: Current ip
  debug:
    msg: "https://{{ ansible_facts.default_ipv4.address }}:80"

- name: Install packeges
  hosts: all
  gather_facts: false
  become: yes
  roles:
    - name: "test"
      role: myrole
      vars:
        username: "Aziz2" 
  
